
Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.network "forwarded_port", guest: 80, host:8090
    config.vm.network "public_network", ip:"192.168.100.200"
    config.vm.provision "shell", inline: "apt-get update -y && apt-get upgrade -y"
    
  end