
Vagrant.configure("2") do |config|

  # Configuração para a VM "Capitão America"
  config.vm.define "capitao-america" do |cap|
    cap.vm.box = "generic/centos9s"
    cap.vm.network "public_network", ip: "192.168.100.101"
    cap.vm.hostname = "capitao-america"
    cap.vm.provision "shell", path: "capamerica.sh"
    #Configurações específicas do provider VirtualBox
    cap.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
      vb.name = "capitao-america"
    end
  end

  # Configuração para a VM "Thor"
  config.vm.define "thor" do |thor|
    thor.vm.box = "debian/bullseye64"
    thor.vm.network "public_network", ip: "192.168.100.102"
    thor.vm.hostname = "thor"
    thor.vm.provision "shell", path: "thor.sh"

    # Configuraçõs específicas do provider VirtualBox
    thor.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
      vb.name = "thor"
    end
  end

  # Configuração para a VM "Thanos"
  config.vm.define "thanos" do |thanos|
    thanos.vm.box = "gusztavvargadr/windows-10"
    thanos.vm.guest = "windows"
    thanos.vm.network "public_network", ip:"192.168.100.103"
    thanos.vm.communicator = "winrm"
    thanos.vm.hostname = "thanos"

    # Configurações específicas do provider VirtualBox
    thanos.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 4
      vb.name = "thanos"
    end
  end
end

