
Vagrant.configure("2") do |config|

config.vm.provider "virtualbox" do |vb|

  config.vm.box = "generic/centos9s"
  config.vm.network = "public_network", ip: "192.168.100.101"
  config.vm.hostname = "capitao-america"
  config.vm.provision "shell", path: "capamerica.sh"
end

  config.vm.box = "debian/bullseye64"
  config.vm.network = "public_network", ip: "192.168.100.102"
  config.vm.hostname = "thor"
  config.vm.provision "shell", path: "thor.sh"
end

  config.vm.box = "gusztavvargadr/windows-10"
  config.vm.guest = "windows"
  config.vm.network = "public_network", ip: "192.168.100.103"
  config.vm.communicator = "winrm"
  config.vm.hostname = "thanos"

