Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "public_network", ip: "192.168.100.203"
  config.vm.synced_folder "../sync", "/var/www/html"
  config.vm.hostname = "sv-web-cep"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    vb.name = "sv-web-cep"
  end
  config.vm.provision "shell", path: "provision.sh"
end
