Vagrant.configure("2") do |config|
  # Definindo qual o SO 
  config.vm.box = "ubuntu/jammy64"
  # Criando redirecionamento de portas para o guest
  config.vm.network "forwarded_port", guest: 80, host: 8080
  # Configurando a Rede como Bridge e definindo IP
  config.vm.network "public_network", ip: "192.168.100.201"
  # Definindo hostname da VM
  config.vm.hostname = "projeto2-jammy"
  # Configurando o Virtualbox para 2Gb de RAM e 2 CPUs
  config.vm.provider "virtualbox" do |vb|
    vb.name = "projeto2"
    vb.memory = "2048"
    vb.cpus = 2
  end
  # Configurando provisionamento de pacotes com shell scipt
  config.vm.provision "shell", path: "provision.sh" 
end
