Vagrant.configure("2") do |config|
  # Box e nome da VM
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "zabbis"

  # Rede pública com IP fixo
  config.vm.network "public_network", ip: "192.168.100.204"
  
  # Configurações do Virtualbox
  config.vm.provider "virtualbox" do |vb|
   vb.memory = "2048"
   vb.cpus = 2
   vb.name = "zabbis"
  end

  # Script de provisionamento
  config.vm.provision "shell", path: "provision.sh"
end
