Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "public_network", ip: "192.168.100.204"
  config.vm.hostname = "zabbis"
  config.vm.provider "virtualbox" do |vb|
   vb.memory = "2048"
   vb.cpus = 2
   vb.name = "zabbis"
  end
  config.vm.provision "shell", path: "provision.sh"
end
